// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB38QpELnHOGF7il3JGGcA36cifOhneYno',
    appId: '1:978810687725:android:09b48e7b105e9c1482fce4',
    messagingSenderId: '978810687725',
    projectId: 'database-x-8991e',
    databaseURL: 'https://database-x-8991e-default-rtdb.firebaseio.com',
    storageBucket: 'database-x-8991e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFVndxzc2l45br3FrW-uU2dQ_TdD_A3io',
    appId: '1:978810687725:ios:9b5c07a81430330382fce4',
    messagingSenderId: '978810687725',
    projectId: 'database-x-8991e',
    databaseURL: 'https://database-x-8991e-default-rtdb.firebaseio.com',
    storageBucket: 'database-x-8991e.appspot.com',
    androidClientId: '978810687725-17bc0ajvk5pq78mg4vuj8n58sb6esim2.apps.googleusercontent.com',
    iosClientId: '978810687725-i7c45qommujbuvsejlk4p7moo27q153v.apps.googleusercontent.com',
    iosBundleId: 'com.xfinitive.xfinitive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFVndxzc2l45br3FrW-uU2dQ_TdD_A3io',
    appId: '1:978810687725:ios:9b5c07a81430330382fce4',
    messagingSenderId: '978810687725',
    projectId: 'database-x-8991e',
    databaseURL: 'https://database-x-8991e-default-rtdb.firebaseio.com',
    storageBucket: 'database-x-8991e.appspot.com',
    iosClientId: '978810687725-i7c45qommujbuvsejlk4p7moo27q153v.apps.googleusercontent.com',
    iosBundleId: 'com.xfinitive.xfinitive',
  );

}